apiVersion: v1
kind: Service
metadata:
  name: rl-eu-pgbouncer
  namespace: default
  labels:
    app: rl-eu-pgbouncer
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: rl-eu-pgbouncer
